language: python
python:
  - 3.8
env:
  - TP_QBITTORRENT_CONFIG_HOST="localhost" TP_QBITTORRENT_CONFIG_PORT="8080" TP_QBITTORRENT_CONFIG_USERNAME="admin" TP_QBITTORRENT_CONFIG_PASSWORD="adminadmin" TP_TVDB_API_KEY="0000" TP_TMDB_API_KEY="1111" TP_GMAIL_APP_PASSWORD="2222"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install codecov
install:
  - pip install .
script: pytest
after_success:
  - codecov
